// Module2_FrontendDev/Madhumitha/handson_05_react/src/components/CourseCard.jsx
export default function CourseCard({
    id,
    name,
    code,
    credits,
    grade,
    onEnroll
}) {
    return (
        <article
            style={{
                background: '#fff',
                border: '1px solid #d1dce8',
                borderRadius: 10,
                padding: 20,
                boxShadow: '0 2px 8px rgba(0,0,0,.08)'
            }}
        >
            <h3 style={{ color: '#0f3460', marginBottom: 8 }}>
                {name}
            </h3>

            <p style={{ color: '#4a5568', marginBottom: 12 }}>
                Code: {code}
            </p>

            <div
                style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center'
                }}
            >
                <span
                    style={{
                        background: '#e8f0fe',
                        color: '#0f3460',
                        padding: '3px 10px',
                        borderRadius: 12,
                        fontSize: '0.8rem',
                        fontWeight: 600
                    }}
                >
                    Credits: {credits}
                </span>

                <span
                    style={{
                        fontWeight: 700,
                        color: grade === 'A' ? '#155724' : '#004085'
                    }}
                >
                    Grade: {grade}
                </span>
            </div>

            {onEnroll && (
                <button
                    onClick={() =>
                        onEnroll({
                            id,
                            name,
                            code,
                            credits,
                            grade
                        })
                    }
                    style={{
                        marginTop: 12,
                        padding: '8px 16px',
                        background: '#0f3460',
                        color: '#fff',
                        border: 'none',
                        borderRadius: 6,
                        cursor: 'pointer',
                        width: '100%'
                    }}
                >
                    + Enroll
                </button>
            )}
        </article>
    );
}

// Module2_FrontendDev/Madhumitha/handson_07_angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <article class="course-card">
      <h3>{{ name }}</h3>
      <p>Code: <strong>{{ code }}</strong></p>
      <div class="card-footer">
        <span class="credits">Credits: {{ credits }}</span>
        <span class="grade">Grade: {{ grade }}</span>
      </div>
    </article>
  `,
  styles: [`
    .course-card { background:#fff; border:1px solid #d1dce8; border-radius:10px;
                   padding:20px; box-shadow:0 2px 8px rgba(0,0,0,.08); }
    .card-footer { display:flex; justify-content:space-between; margin-top:12px; }
    .credits { background:#e8f0fe; color:#0f3460; padding:3px 10px; border-radius:12px; font-size:0.8rem; }
    .grade { font-weight:700; color:#0f3460; }
  `]
})
export class CourseCardComponent {
  @Input() name!: string;
  @Input() code!: string;
  @Input() credits!: number;
  @Input() grade!: string;
}
